version: '3.8'

services:
  aci-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: aci-automacoes-prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env.local
    restart: always
    networks:
      - aci-prod-network
    volumes:
      - aci-prod-logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aci-prod.rule=Host(`seu-dominio.com`)"
      - "traefik.http.routers.aci-prod.tls=true"
      - "traefik.http.routers.aci-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.aci-prod.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  aci-prod-network:
    driver: bridge

volumes:
  aci-prod-logs:
    driver: local